name: Python Hello World

on: [push]

jobs:
  python-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Definir variable
      run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
    - name: print hello world
      run: python helloWorld.py
